export enum NumericalFeatures {
  DEFAULT = "DEFAULT",
  CURRENT = "CURRENT",
  LAST = "LAST",
  MAX = "MAX",
  MIN = "MIN",
  PEAK = "PEAK",
  VALLEY = "VALLEY",
  FALL = "FALL",
  RAISE = "RAISE",
  SLOPE = "SLOPE",
  ML_CURRENT = "ML_CURRENT",
  ML_LAST = "ML_LAST",
  ML_MAX = "ML_MAX",
  ML_MIN = "ML_MIN",
}
